import { SynthesisResult } from './types'

export const MOCK_RESULT: SynthesisResult = {
  question: 'Should governments regulate artificial intelligence?',
  evidence: [
    {
      sourceTitle: 'Wikipedia: Regulation of artificial intelligence',
      sourceURL: 'https://en.wikipedia.org/wiki/Regulation_of_artificial_intelligence',
      claim: 'The regulation of artificial intelligence is considered by different governments around the world. AI regulation aims to address concerns about safety, fairness, and accountability in AI systems deployed across critical sectors.',
      confidence: 82,
      type: 'supporting',
    },
    {
      sourceTitle: 'Wikipedia: Artificial intelligence safety',
      sourceURL: 'https://en.wikipedia.org/wiki/Artificial_intelligence_safety',
      claim: 'AI safety research aims to ensure that AI systems behave in safe and beneficial ways. Critics argue that regulation may stifle innovation while proponents say it is necessary to prevent catastrophic risks.',
      confidence: 78,
      type: 'neutral',
    },
    {
      sourceTitle: 'Wikipedia: EU AI Act',
      sourceURL: 'https://en.wikipedia.org/wiki/Artificial_Intelligence_Act',
      claim: 'The EU AI Act is the world\'s first comprehensive legal framework on artificial intelligence, categorizing AI systems by risk level and imposing requirements on high-risk applications.',
      confidence: 91,
      type: 'supporting',
    },
    {
      sourceTitle: 'Wikipedia: Innovation economics',
      sourceURL: 'https://en.wikipedia.org/wiki/Innovation_economics',
      claim: 'Research on technology regulation shows complex tradeoffs: excessive regulation can reduce innovation and competitive advantage while insufficient regulation allows harms to accumulate before being addressed.',
      confidence: 74,
      type: 'opposing',
    },
  ],
  round1: [
    {
      agentId: 'skeptic',
      position: 'The case for AI regulation is strong but the implementation evidence is thin. Existing regulations like GDPR show meaningful rights protection but also compliance overhead that disproportionately affects smaller actors. We need to demand that proponents specify what harms they are regulating against, with what mechanisms, enforced by whom.',
      key_claims: [
        'Most proposed AI regulations lack falsifiable success criteria',
        'Algorithmic harms are real and documented: hiring bias, credit discrimination, wrongful arrest via facial recognition',
        'Regulatory capture is a serious risk — industry may shape rules to entrench incumbents',
      ],
      confidence: 64,
      one_liner: 'Show me the evidence that the proposed regulation actually solves the identified harm.',
      reasoning_style: 'empirical',
      citations: [
        { claim: 'Facial recognition misidentification rates are significantly higher for darker-skinned individuals', supportingEvidence: ['NIST FRVT study showing 10-100x higher error rates across demographic groups'], confidence: 89 },
        { claim: 'GDPR compliance costs fall heavily on small organizations', supportingEvidence: ['EU Commission impact assessments showing SME compliance burden'], confidence: 76 },
      ],
    },
    {
      agentId: 'advocate',
      position: 'Government regulation of AI is not only warranted but urgently necessary. The EU AI Act demonstrates that smart, risk-tiered regulation is achievable without prohibiting innovation. Left unregulated, AI systems will optimize for measurable proxies over human values, causing systematic harm at scale.',
      key_claims: [
        'Market incentives systematically underweight externalities and long-term risks',
        'The EU AI Act provides a workable template: risk-tiered, sector-specific, innovation-friendly',
        'Without accountability mechanisms, AI developers have no incentive to invest in safety',
      ],
      confidence: 81,
      one_liner: 'Markets optimized nuclear power, pharmaceuticals, and aviation only after regulation made safety profitable.',
      reasoning_style: 'advocacy',
      citations: [
        { claim: 'Aviation safety dramatically improved after the FAA established binding certification requirements', supportingEvidence: ['NTSB historical accident data showing post-regulation improvement'], confidence: 85 },
        { claim: 'The EU AI Act categorizes systems by risk and applies proportionate requirements', supportingEvidence: ['EU AI Act official text, risk classification framework'], confidence: 93 },
      ],
    },
    {
      agentId: 'devil',
      position: 'Government AI regulation will predictably fail for the same reasons software regulation has always failed: governments lack the technical expertise, move too slowly, and get captured by incumbents who write the rules. The cure is likely worse than the disease.',
      key_claims: [
        'Regulatory agencies consistently lack technical expertise to assess AI systems meaningfully',
        'Compliance-based regulation creates checkbox mentality that substitutes for actual safety',
        'China will not reciprocate — unilateral Western regulation creates geopolitical disadvantage',
      ],
      confidence: 74,
      one_liner: 'You cannot regulate what you cannot measure, and governments cannot measure what they do not understand.',
      reasoning_style: 'contrarian',
      citations: [
        { claim: 'SEC, FTC, and FDA have historically struggled to regulate rapidly evolving technology sectors', supportingEvidence: ['Academic literature on regulatory lag in technology sectors'], confidence: 71 },
      ],
    },
    {
      agentId: 'expert',
      position: 'From a technical standpoint, effective AI regulation requires distinguishing between model capabilities, deployment contexts, and downstream impacts. Current legislative proposals conflate these layers, making them simultaneously overbroad and under-inclusive. Technical standards bodies, not legislatures, are better positioned to develop meaningful AI governance frameworks.',
      key_claims: [
        'AI risk depends on deployment context, not model architecture — regulating models is technically incoherent',
        'Interpretability and auditing tools are insufficiently mature to support compliance verification',
        'Technical standards (like ISO 42001) can move faster and with more precision than legislation',
      ],
      confidence: 77,
      one_liner: 'You cannot audit a neural network the way you audit a financial statement — and most AI regulation assumes you can.',
      reasoning_style: 'technical',
      citations: [
        { claim: 'Current XAI methods provide post-hoc rationalizations, not true mechanistic explanations', supportingEvidence: ['Lipton (2018) "The Mythos of Model Interpretability" and subsequent replication literature'], confidence: 82 },
      ],
    },
    {
      agentId: 'ethicist',
      position: 'The ethical imperative for AI regulation is clear: without it, the most vulnerable populations bear the costs while benefits accrue to the already powerful. But ethics also demands honest acknowledgment that poorly designed regulation can itself cause harm by locking in current power structures or reducing access to beneficial AI.',
      key_claims: [
        'Unregulated AI perpetuates and amplifies existing social inequities',
        'Vulnerable populations — minorities, low-income communities, disabled individuals — bear disproportionate AI risks',
        'Procedural justice requires that affected communities have meaningful input in regulatory design',
      ],
      confidence: 79,
      one_liner: 'The question is not whether to regulate, but who gets to shape the rules and who bears the costs of getting them wrong.',
      reasoning_style: 'moral',
      citations: [
        { claim: 'Algorithmic decision systems in criminal justice, hiring, and credit have documented disparate impacts', supportingEvidence: ['ProPublica COMPAS analysis, HireVue bias studies, Urban Institute housing algorithm research'], confidence: 87 },
      ],
    },
    {
      agentId: 'contrarian',
      position: 'The entire framing of this debate is wrong. "Government regulation of AI" treats AI as a single thing — it is not. Regulating ChatGPT and regulating an autonomous weapons system are completely different problems. The real question nobody is asking: should AI companies self-govern, and if not, what makes us think governments will do better?',
      key_claims: [
        'AI is not a single technology — the debate needs to specify which AI, for what purpose, causing what harm',
        'Self-regulatory bodies (IEEE, NIST, ACM) may be more technically capable than government agencies',
        'The most dangerous AI applications are military — and no one is seriously proposing to regulate those',
      ],
      confidence: 69,
      one_liner: 'Everyone is debating the wrong question — the real question is who can regulate effectively, not whether regulation is good.',
      reasoning_style: 'lateral',
      citations: [],
    },
    {
      agentId: 'statistician',
      position: 'The empirical evidence on technology regulation is mixed with wide confidence intervals. Studies on GDPR show 12-18% reduction in data-intensive startups, but also measurable improvements in privacy outcomes. The base rate of new technology causing net harm without regulation is historically ~40% for transformative technologies, suggesting precautionary regulation is Bayesian-rational.',
      key_claims: [
        'GDPR implementation reduced VC investment in European tech startups by an estimated 12-18% (Jia et al., 2019)',
        'Historical base rate: ~40% of transformative technologies required post-hoc regulatory correction for significant harms',
        'Probability estimates for transformative AI causing catastrophic harm range from 5% to 50% depending on modeling assumptions — a range too wide to ignore',
      ],
      confidence: 71,
      one_liner: 'Wide confidence intervals on catastrophic risk plus asymmetric downside strongly favors the precautionary position.',
      reasoning_style: 'quantitative',
      citations: [
        { claim: 'GDPR reduced VC funding in data-intensive sectors by an estimated 17.6%', supportingEvidence: ['Jia, Jin, Wagman (2019) "The Short-Run Effects of GDPR on Technology Venture Investment"'], confidence: 78 },
      ],
    },
    {
      agentId: 'historian',
      position: 'Historical precedent strongly favors proactive AI regulation. Every comparable transformative technology — railroads, electricity, pharmaceuticals, nuclear power, aviation, the internet — eventually required government intervention to prevent systematic harm. The question is not if but when, and early regulation is consistently less costly than reactive regulation after harm accumulates.',
      key_claims: [
        'The railroad era, pharmaceutical revolution, and aviation all required significant regulatory intervention after initial market failures',
        'Late regulatory intervention is consistently more disruptive and costly than proactive frameworks',
        'The internet provides a cautionary tale: early failure to regulate has produced documented social harms that are now much harder to address',
      ],
      confidence: 83,
      one_liner: 'Every transformative technology eventually gets regulated — the only question is how much harm accumulates first.',
      reasoning_style: 'historical',
      citations: [
        { claim: 'The Food and Drug Act of 1906 came only after documented deaths from patent medicines, not before', supportingEvidence: ['FDA historical records, Harvey Wiley correspondence'], confidence: 91 },
        { claim: 'Internet platform harms have proven extremely difficult to regulate retroactively once business models are entrenched', supportingEvidence: ['FTC v. Facebook, Section 230 reform failures, EU DSA comparison'], confidence: 79 },
      ],
    },
    {
      agentId: 'systems',
      position: 'AI regulation will create feedback loops that its designers cannot fully anticipate. Large regulatory frameworks tend to create compliance bureaucracies that favor large incumbents, paradoxically concentrating AI development in the very entities most capable of causing large-scale harm. The regulatory system itself will become a system with emergent properties.',
      key_claims: [
        'Compliance overhead creates barriers to entry that concentrate AI development in large incumbents',
        'Regulatory capture feedback loop: regulated entities fund lobbying → shape regulations → reduce competition → increase their own power',
        'International regulatory arbitrage will route development to least-regulated jurisdictions, potentially increasing global risk',
      ],
      confidence: 73,
      one_liner: 'Regulating a complex adaptive system with linear rules produces emergent outcomes that undermine the regulatory intent.',
      reasoning_style: 'systemic',
      citations: [],
    },
  ],
  round2: [
    { agentId: 'skeptic', challenged_assumptions: ['That regulatory agencies have or will acquire sufficient technical expertise', 'That the EU AI Act will generalize outside the EU context'], fallacies_identified: ['Advocate commits appeal to aviation analogy — aviation is a closed, well-defined system; AI is not'], strongest_opposing_argument: 'The historian\'s point about late intervention costs is empirically strong and hard to refute.', confidence: 66 },
    { agentId: 'advocate', challenged_assumptions: ['That regulatory capture is inevitable rather than preventable by design', 'That technical complexity makes regulation impossible'], fallacies_identified: ['Devil\'s Advocate commits nirvana fallacy: imperfect regulation vs. perfect no-regulation'], strongest_opposing_argument: 'The systems thinker\'s regulatory capture feedback loop is the strongest argument for careful regulatory design.', confidence: 78 },
    { agentId: 'devil', challenged_assumptions: ['That government agencies cannot be technically competent — the FTC Bureau of Economics and FDA CDER show this is not inevitable'], fallacies_identified: ['Historian\'s tech analogy assumes regulatory success rate we don\'t have — survival bias in the examples chosen'], strongest_opposing_argument: 'The statistician\'s asymmetric downside argument is the most intellectually honest case for regulation.', confidence: 70 },
    { agentId: 'expert', challenged_assumptions: ['That self-governance by standards bodies is reliable — IEEE standards are voluntary and have no enforcement mechanism'], fallacies_identified: ['Conflation of capability regulation (hard) with deployment regulation (more feasible)'], strongest_opposing_argument: 'The ethicist is correct that technical governance without democratic legitimacy has its own serious problems.', confidence: 72 },
    { agentId: 'ethicist', challenged_assumptions: ['That regulation designed by current institutions will actually include marginalized voices in practice'], fallacies_identified: ['Statistician\'s numbers feel rigorous but the 40% base rate is not falsifiable given technology heterogeneity'], strongest_opposing_argument: 'The contrarian\'s point about military AI being the most dangerous and least regulated is ethically the most urgent.', confidence: 81 },
    { agentId: 'contrarian', challenged_assumptions: ['Everyone assumes this is a technical problem solvable with the right rules — it may be fundamentally a political economy problem'], fallacies_identified: ['Historian commits post hoc ergo propter hoc: regulation followed harm in past cases, but correlation is not causation'], strongest_opposing_argument: 'The systems thinker is the only one accurately modeling the second-order effects of regulatory implementation.', confidence: 65 },
    { agentId: 'statistician', challenged_assumptions: ['That catastrophic AI risk estimates from AI safety researchers are unbiased — publication and advocacy incentives may inflate risk estimates'], fallacies_identified: ['All agents except systems thinker ignore the counterfactual: what is the evidence base rate for beneficial AI without regulation?'], strongest_opposing_argument: 'The historian\'s analysis of regulatory timing is the most quantitatively defensible argument in the debate.', confidence: 69 },
    { agentId: 'historian', challenged_assumptions: ['That contemporary AI innovation resembles pre-regulatory industrial technologies — the speed differential is unprecedented'], fallacies_identified: ['Devil\'s Advocate\'s China geopolitical argument is historically unfalsifiable and has been used to resist regulation in every tech domain'], strongest_opposing_argument: 'The expert\'s technical point about interpretability maturity is a genuine constraint on effective regulation implementation.', confidence: 84 },
    { agentId: 'systems', challenged_assumptions: ['That regulatory systems have identifiable equilibria — complex adaptive systems rarely do'], fallacies_identified: ['Both advocate and skeptic reason about regulation as if it has a single stable effect rather than evolving impact over time'], strongest_opposing_argument: 'The statistician\'s Bayesian framing is the most systemic approach: we are updating on evidence in real time, not solving a static problem.', confidence: 71 },
  ],
  round3: [
    { agentId: 'skeptic', revised_position: 'After three rounds, my position is refined: context-specific, harm-defined regulation with built-in falsifiability criteria is both necessary and achievable. I now accept the historian\'s historical precedent argument and the statistician\'s asymmetric risk framing. The key issue is operational specificity, not whether to regulate.', held_firm: false, strongest_claim: 'Any regulation must define specific measurable harms, enforcement mechanisms, and success criteria before implementation', defense: 'Regulatory effectiveness is empirically testable — we should demand ex ante success criteria and ex post evaluation', agreements: ['Historical pattern of technology eventually requiring regulation', 'Asymmetric downside risk justifies precautionary approach'], challenged_claims: ['The analogy to aviation is oversimplified — aviation has clear failure modes, AI harms are diffuse and probabilistic'], confidence_delta: 8, final_confidence: 72 },
    { agentId: 'advocate', revised_position: 'The systems thinker\'s regulatory capture concerns have genuinely strengthened my position on design quality. I maintain that regulation is necessary but now emphasize: adaptive regulation with mandatory review cycles, multi-stakeholder governance, and sunset clauses to prevent entrenchment. Good regulatory design can mitigate the second-order effects.', held_firm: true, strongest_claim: 'Adaptive, risk-tiered regulation with democratic accountability is both achievable and urgently needed', defense: 'The EU AI Act and NIST frameworks demonstrate that technically competent regulation is achievable with proper institutional design', agreements: ['Regulatory capture is a serious design constraint', 'Technical standards bodies should co-design with democratic institutions'], challenged_claims: ['That regulatory complexity inevitably benefits incumbents — proportionality rules can address this'], confidence_delta: 3, final_confidence: 84 },
    { agentId: 'devil', revised_position: 'The statistician\'s asymmetric downside argument has moved me. I now concede that some regulatory intervention is probably warranted for high-stakes AI deployments. However, I maintain that comprehensive AI regulation is likely to fail and that lighter-touch liability frameworks — where developers bear costs of harms — may be more effective than prescriptive rules.', held_firm: false, strongest_claim: 'Strict liability for AI-caused harms is more effective than compliance-based regulation because it aligns incentives', defense: 'Pharmaceutical liability law shows that financial consequences are more powerful than regulatory checklists for incentivizing safety', agreements: ['High-risk AI deployments require some accountability mechanism', 'Asymmetric downside risk strengthens the case for precaution'], challenged_claims: ['That comprehensive AI regulation will be technically competent enough to be effective'], confidence_delta: -6, final_confidence: 68 },
    { agentId: 'expert', revised_position: 'My technical concerns remain but I now accept that "perfect should not be the enemy of good" in regulatory policy. Regulation based on deployment risk and outcome monitoring, rather than model auditing, is technically feasible. I advocate strongly for co-development of standards with NIST, IEEE, and ISO alongside legislative frameworks.', held_firm: false, strongest_claim: 'Outcome-based regulation monitoring for deployment impacts is technically feasible and should replace model-level auditing requirements', defense: 'We can measure discrimination in credit decisions, detect errors in medical AI outputs, and monitor for systematic failures — these are tractable measurement problems', agreements: ['Democratic legitimacy requires legislative action, not just technical standards', 'High-risk applications need mandatory incident reporting and audit requirements'], challenged_claims: ['That general-purpose AI can be meaningfully regulated at the model level — this remains technically unfeasible'], confidence_delta: 5, final_confidence: 82 },
    { agentId: 'ethicist', revised_position: 'My ethical analysis holds throughout. The debate has reinforced that regulatory process justice is as important as regulatory outcomes. Any AI governance framework that does not include meaningful participation from affected communities — especially marginalized ones — will be ethically deficient regardless of its technical quality.', held_firm: true, strongest_claim: 'Procedural justice demands that those most likely to be harmed by AI systems must have meaningful input in shaping governance frameworks', defense: 'Democratic legitimacy of AI regulation depends on inclusion; regulation without representation reproduces the power dynamics that make AI harmful in the first place', agreements: ['Adaptive regulation with mandatory review is superior to static frameworks', 'Military AI regulation is the most ethically urgent gap that this entire debate has underweighted'], challenged_claims: ['That technical standards bodies can substitute for democratic governance processes — they cannot'], confidence_delta: 6, final_confidence: 85 },
    { agentId: 'contrarian', revised_position: 'The debate has confirmed my core reframing: the question "should governments regulate AI" is too vague to answer meaningfully. Different AI applications require completely different governance approaches. My evolved position: governments should regulate specific AI deployment contexts (hiring, credit, criminal justice, healthcare, autonomous weapons) rather than "AI" as a category.', held_firm: true, strongest_claim: 'Deployment-context-specific regulation of high-stakes AI applications is both more achievable and more effective than general AI regulation', defense: 'Sector-specific AI regulation (medical AI via FDA, financial AI via SEC/CFPB) already exists and has a track record to learn from', agreements: ['The historian is right that later regulation is costlier', 'The systems thinker is right about emergent regulatory dynamics'], challenged_claims: ['That a single comprehensive AI regulation framework is the right level of abstraction — it is too broad to be meaningful'], confidence_delta: 4, final_confidence: 73 },
    { agentId: 'statistician', revised_position: 'My probability estimates remain: given 40% historical base rate of technology harms requiring regulatory correction, asymmetric catastrophic downside, and current model of AI progress, the expected value calculation favors regulatory intervention. The wide confidence intervals on AI risk estimates do not argue against regulation — they argue for adaptive regulation with built-in uncertainty accommodation.', held_firm: true, strongest_claim: 'Bayesian expected value calculation under uncertainty strongly favors precautionary regulation even with wide confidence intervals on harm probability', defense: 'Under asymmetric risk (catastrophic downside, manageable upside loss from over-regulation), the optimal decision under uncertainty is precautionary', agreements: ['Adaptive regulation with mandatory evidence review is the correct response to wide uncertainty', 'Regulatory implementation quality matters enormously for whether the expected value is positive or negative'], challenged_claims: ['That perfect regulatory design is achievable — we should model regulatory implementation as itself uncertain'], confidence_delta: 2, final_confidence: 73 },
    { agentId: 'historian', revised_position: 'History speaks clearly on this question. The pattern is invariant across railroads, pharmaceuticals, aviation, nuclear, and the internet: transformative technologies cause systematic harm, markets fail to self-correct, regulation eventually follows, and early regulation is consistently less costly than reactive regulation. The internet failure is especially instructive for AI.', held_firm: true, strongest_claim: 'Early regulation is consistently less costly than reactive regulation — the internet provides the most instructive cautionary precedent for AI', defense: 'We have natural experiments: telecommunications with and without early regulation, pharmaceuticals with and without pre-market approval — early regulation wins on net harm outcomes', agreements: ['Context-specific regulation by deployment domain makes historical sense', 'Adaptive regulation that updates with the technology is the lesson from telecommunications history'], challenged_claims: ['That AI\'s speed of development makes historical precedent inapplicable — the speed changes timelines, not the fundamental regulatory economics'], confidence_delta: 5, final_confidence: 88 },
    { agentId: 'systems', revised_position: 'My systems analysis reveals the core dilemma: any effective AI regulation must grapple with its own emergent effects on the system it regulates. I now advocate for regulatory sandboxes, adaptive governance frameworks, and mandatory feedback loops rather than static rules. The goal should be a regulatory system that can learn and adapt as AI capabilities evolve.', held_firm: true, strongest_claim: 'An adaptive regulatory system with built-in learning mechanisms is necessary because static rules cannot govern a rapidly evolving complex system', defense: 'Sandbox regulation models from financial technology show that learning-oriented regulatory frameworks can maintain safety while accommodating innovation', agreements: ['Proportional, context-specific regulation reduces the compliance concentration problem', 'Mandatory incident reporting creates the feedback loops necessary for adaptive governance'], challenged_claims: ['That any regulatory framework can fully anticipate and prevent regulatory capture — the systems view says capture is an attractor state that requires constant counter-pressure'], confidence_delta: 4, final_confidence: 77 },
  ],
  phase1: [],
  phase2: [],
  consensus: {
    agreed: [
      'Some form of governance framework for AI in high-risk domains (healthcare, criminal justice, hiring, credit) is both necessary and achievable',
      'Early regulatory intervention is likely less costly than reactive regulation after significant harms accumulate',
      'Adaptive, context-specific regulation is superior to a single comprehensive AI law',
      'Democratic legitimacy requires that affected communities — especially vulnerable populations — have meaningful participation in AI governance design',
    ],
    contested: [
      'Whether comprehensive national AI legislation (like the EU AI Act) is more effective than sector-specific agency regulation',
      'Whether liability-based approaches (make developers pay for harms) can substitute for prescriptive compliance frameworks',
      'Whether regulatory complexity inevitably concentrates AI development among large incumbents',
    ],
    unresolved: [
      'How to regulate general-purpose AI systems whose harms are diffuse and not attributable to specific deployments',
      'Whether international regulatory coordination is achievable given geopolitical competition, especially regarding China',
      'How to govern military and national security AI applications, which remain largely outside civilian regulatory frameworks',
    ],
    confidence: 74,
    synthesis: 'The debate reached strong convergence on the necessity of AI governance but diverged on implementation approach. A clear majority position emerged: deployment-context-specific, adaptive regulation with democratic accountability mechanisms is both necessary and more achievable than comprehensive AI legislation. The most significant unresolved tension is between innovation competition and precautionary safety governance at the international level.',
    recommendation: 'A rational actor should conclude: (1) High-risk AI deployment contexts — healthcare, criminal justice, hiring, credit, autonomous systems — require mandatory governance frameworks now. (2) These frameworks should be adaptive, with mandatory review cycles and outcome monitoring rather than static compliance checklists. (3) General-purpose AI foundation models need disclosure and incident-reporting requirements as a minimum. (4) International coordination on AI governance norms should be treated as a global public goods problem requiring multilateral negotiation.',
    strongest_argument: 'The historian\'s analysis carries the most evidential weight: every comparable transformative technology eventually required regulatory intervention, and the cost of late intervention consistently exceeded the cost of proactive frameworks. Combined with the statistician\'s asymmetric risk framing — where wide uncertainty intervals do not argue against precaution but for it — the case for proactive AI governance is robust across epistemic frameworks.',
    biggest_blind_spot: 'The entire debate significantly underweighted military and national security AI applications, which arguably represent the greatest near-term catastrophic risk and are the least subject to any proposed civilian regulatory framework. The ethicist raised this but it was not adequately addressed by any other agent.',
    weighted_claims: [
      { claim: 'High-risk AI applications require mandatory governance', confidence: 88, support_count: 8, opposition_count: 1, evidence_quality: 84, category: 'high' },
      { claim: 'Early regulation is less costly than reactive regulation historically', confidence: 82, support_count: 7, opposition_count: 2, evidence_quality: 79, category: 'high' },
      { claim: 'Adaptive regulation is superior to static comprehensive frameworks', confidence: 79, support_count: 7, opposition_count: 2, evidence_quality: 71, category: 'moderate' },
      { claim: 'Comprehensive AI legislation will be subject to regulatory capture', confidence: 68, support_count: 5, opposition_count: 4, evidence_quality: 62, category: 'contested' },
      { claim: 'Unilateral Western regulation creates geopolitical competitive disadvantage', confidence: 54, support_count: 3, opposition_count: 6, evidence_quality: 48, category: 'contested' },
      { claim: 'AI regulation cannot be technically competent given current government expertise', confidence: 41, support_count: 2, opposition_count: 7, evidence_quality: 55, category: 'minority' },
    ],
    fact_checks: [
      { claim: 'GDPR reduced VC investment in European data-intensive startups by 12-18%', verdict: 'verified', reason: 'Supported by Jia, Jin, Wagman (2019) peer-reviewed study, though effect size varies by methodology' },
      { claim: 'Facial recognition error rates are 10-100x higher for darker-skinned individuals', verdict: 'verified', reason: 'Confirmed by NIST FRVT 2019 evaluation and MIT Media Lab Gender Shades study' },
      { claim: 'The EU AI Act is the world\'s first comprehensive AI legal framework', verdict: 'verified', reason: 'Accurate as of 2024; no comparable comprehensive AI legislation exists in other major jurisdictions' },
      { claim: '40% base rate of transformative technologies requiring regulatory correction', verdict: 'low_confidence', reason: 'Plausible heuristic but no peer-reviewed source for this specific base rate; technology classification is non-trivial' },
    ],
    evidence_summary: 'The retrieved evidence (Wikipedia: EU AI Act, AI Safety, Technology Regulation) supported the regulatory necessity case and confirmed factual claims about existing frameworks. Evidence was insufficient to resolve empirical disputes about international competitiveness effects or optimal regulatory design.',
    uncertainty_note: 'These conclusions would shift significantly if: (1) AI capabilities advance dramatically faster than current trajectories, making any current regulatory framework obsolete; (2) empirical evidence on EU AI Act outcomes (expected 2025-2027) shows significant innovation chilling effects; (3) US-China AI regulatory coordination becomes more or less feasible than currently expected.',
  },
  graph: {
    nodes: [
      { id: 'q0', label: 'Should governments regulate AI?', type: 'question', size: 26, color: '#EEEEF8' },
      { id: 'ev-0', label: 'EU AI Act (Wikipedia)', type: 'evidence', size: 12, color: '#57E4FF' },
      { id: 'ev-1', label: 'AI Safety Research (Wikipedia)', type: 'evidence', size: 10, color: '#57E4FF' },
      { id: 'a-skeptic', label: 'The Skeptic', type: 'agent', agentId: 'skeptic', color: '#FF5757', size: 18 },
      { id: 'a-advocate', label: 'The Advocate', type: 'agent', agentId: 'advocate', color: '#57C4FF', size: 18 },
      { id: 'a-devil', label: "Devil's Advocate", type: 'agent', agentId: 'devil', color: '#FFD557', size: 18 },
      { id: 'a-expert', label: 'The Expert', type: 'agent', agentId: 'expert', color: '#57FFB8', size: 18 },
      { id: 'a-ethicist', label: 'The Ethicist', type: 'agent', agentId: 'ethicist', color: '#C057FF', size: 18 },
      { id: 'a-contrarian', label: 'The Contrarian', type: 'agent', agentId: 'contrarian', color: '#FF8557', size: 18 },
      { id: 'a-statistician', label: 'The Statistician', type: 'agent', agentId: 'statistician', color: '#57E4FF', size: 18 },
      { id: 'a-historian', label: 'The Historian', type: 'agent', agentId: 'historian', color: '#FFAA57', size: 18 },
      { id: 'a-systems', label: 'Systems Thinker', type: 'agent', agentId: 'systems', color: '#B457FF', size: 18 },
      { id: 'c-sk-0', label: 'Regulations lack falsifiable criteria', type: 'claim', agentId: 'skeptic', color: '#FF5757', size: 9 },
      { id: 'c-sk-1', label: 'Algorithmic harms are documented', type: 'claim', agentId: 'skeptic', color: '#FF5757', size: 9 },
      { id: 'c-av-0', label: 'Markets underweight externalities', type: 'claim', agentId: 'advocate', color: '#57C4FF', size: 9 },
      { id: 'c-av-1', label: 'EU AI Act is workable template', type: 'claim', agentId: 'advocate', color: '#57C4FF', size: 11 },
      { id: 'c-hi-0', label: 'Early regulation is less costly', type: 'claim', agentId: 'historian', color: '#FFAA57', size: 13 },
      { id: 'c-st-0', label: 'Asymmetric downside risk', type: 'claim', agentId: 'statistician', color: '#57E4FF', size: 12 },
      { id: 'c-sy-0', label: 'Regulatory capture feedback loop', type: 'claim', agentId: 'systems', color: '#B457FF', size: 10 },
      { id: 'con-0', label: 'High-risk AI requires governance', type: 'consensus', color: '#B4FF57', size: 16 },
      { id: 'con-1', label: 'Adaptive regulation is superior', type: 'consensus', color: '#B4FF57', size: 14 },
      { id: 'con-2', label: 'Military AI is unaddressed gap', type: 'consensus', color: '#FFD557', size: 12 },
    ],
    edges: [
      { id: 'eq-sk', source: 'q0', target: 'a-skeptic', type: 'member', weight: 1 },
      { id: 'eq-av', source: 'q0', target: 'a-advocate', type: 'member', weight: 1 },
      { id: 'eq-dv', source: 'q0', target: 'a-devil', type: 'member', weight: 1 },
      { id: 'eq-ex', source: 'q0', target: 'a-expert', type: 'member', weight: 1 },
      { id: 'eq-et', source: 'q0', target: 'a-ethicist', type: 'member', weight: 1 },
      { id: 'eq-co', source: 'q0', target: 'a-contrarian', type: 'member', weight: 1 },
      { id: 'eq-st', source: 'q0', target: 'a-statistician', type: 'member', weight: 1 },
      { id: 'eq-hi', source: 'q0', target: 'a-historian', type: 'member', weight: 1 },
      { id: 'eq-sy', source: 'q0', target: 'a-systems', type: 'member', weight: 1 },
      { id: 'ev-q0', source: 'ev-0', target: 'q0', type: 'cites', weight: 1.5 },
      { id: 'ev-q1', source: 'ev-1', target: 'q0', type: 'cites', weight: 1.5 },
      { id: 'ec-sk-0', source: 'a-skeptic', target: 'c-sk-0', type: 'supports', weight: 2 },
      { id: 'ec-sk-1', source: 'a-skeptic', target: 'c-sk-1', type: 'supports', weight: 2 },
      { id: 'ec-av-0', source: 'a-advocate', target: 'c-av-0', type: 'supports', weight: 2 },
      { id: 'ec-av-1', source: 'a-advocate', target: 'c-av-1', type: 'supports', weight: 2 },
      { id: 'ec-hi-0', source: 'a-historian', target: 'c-hi-0', type: 'supports', weight: 2 },
      { id: 'ec-st-0', source: 'a-statistician', target: 'c-st-0', type: 'supports', weight: 2 },
      { id: 'ec-sy-0', source: 'a-systems', target: 'c-sy-0', type: 'supports', weight: 2 },
      { id: 'ch-dv-av', source: 'a-devil', target: 'c-av-1', type: 'contradicts', weight: 1.5 },
      { id: 'ch-sk-av', source: 'a-skeptic', target: 'c-av-0', type: 'questions', weight: 1 },
      { id: 'ag-av-hi', source: 'a-advocate', target: 'c-hi-0', type: 'supports', weight: 1.5 },
      { id: 'ag-et-st', source: 'a-ethicist', target: 'c-st-0', type: 'supports', weight: 1 },
      { id: 'con-av', source: 'a-advocate', target: 'con-0', type: 'supports', weight: 2 },
      { id: 'con-hi', source: 'a-historian', target: 'con-0', type: 'supports', weight: 2 },
      { id: 'con-et', source: 'a-ethicist', target: 'con-0', type: 'supports', weight: 2 },
      { id: 'con-ad', source: 'a-contrarian', target: 'con-1', type: 'supports', weight: 1.5 },
      { id: 'con-sy', source: 'a-systems', target: 'con-1', type: 'supports', weight: 1.5 },
      { id: 'con-et2', source: 'a-ethicist', target: 'con-2', type: 'supports', weight: 2 },
    ],
  },
  duration_ms: 14320,
}

// Populate legacy phase1/phase2 from round data
MOCK_RESULT.phase1 = MOCK_RESULT.round1
MOCK_RESULT.phase2 = MOCK_RESULT.round3
